name: Deploy Hexo to GitHub Pages

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main
    paths:
      - 'source/**'
      - '_config.yml'
      - '_config.butterfly.yml'
      - 'themes/**'
      - 'scaffolds/**'
      - 'package.json'
  workflow_run:
    workflows: ['Fetch Email Comments']
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6.0.3
        with:
          submodules: false

      - uses: actions/setup-node@v6.4.0
        with:
          node-version: '24'

      - run: npm ci

      - run: npx hexo generate

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/ -f
          git commit -m "Site updated" || echo "No changes"
          git push
